[package]
name = "obegraensad-pico"
version.workspace = true
authors.workspace = true
description = "Raspberry Pi Pico firmware for IKEA's OBEGRÄNSAD LED display"
edition.workspace = true

[[bin]]
name = "obegraensad-pico"
path = "src/main.rs"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal.workspace = true
fugit.workspace = true
obegraensad-core = { path = "../../core" }
panic-halt = "0.2"
portable-atomic = { version = "1.6", default-features = false, features = ["require-cas", "critical-section"] }
rp-pico = "0.9"
